server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "https://es01:9200" ]

# xpack.security.authc.providers:
#   anonymous.anonymous1:
#     order: 0
#     credentials:
#       username: "anonymous_service_account"
#       password: "anonymous_service_account_password"
